apiVersion: v1
kind: Pod
metadata:
  name: fuel-bot-pod
  labels:
    app: fuel-expense-bot
spec:
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  containers:
    - name: fuel-bot-db
      image: docker.io/library/mariadb:12.2
      env:
        - name: MARIADB_ROOT_PASSWORD
          value: root_internal_pass
        - name: MARIADB_DATABASE
          value: fuel_expense_bot
        - name: MARIADB_USER
          value: fuel_bot
        - name: MARIADB_PASSWORD
          value: fuel_bot_internal_pass
      volumeMounts:
        - name: fuel-bot-data
          mountPath: /var/lib/mysql
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
      livenessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - mariadb -u fuel_bot -pfuel_bot_internal_pass fuel_expense_bot -e "SELECT 1"
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 3
    - name: fuel-bot-app
      image: localhost/fuel-bot:latest
      env:
        - name: TELEGRAM_TOKEN
          value: "${TELEGRAM_TOKEN}"
        - name: DEFAULT_LIMIT
          value: "210.00"
        - name: RUST_LOG
          value: telegram_fuel_bot=info
    # Adminer - Database management UI
    # Access at http://localhost:8080
    # Login: Server=127.0.0.1, Username=fuel_bot, Password=fuel_bot_internal_pass, Database=fuel_expense_bot
    - name: adminer
      image: docker.io/library/adminer:latest
      env:
        - name: ADMINER_DEFAULT_SERVER
          value: "127.0.0.1"
      ports:
        - containerPort: 8080
          hostPort: 8080
  volumes:
    - name: fuel-bot-data
      persistentVolumeClaim:
        claimName: fuel-bot-pvc
    - name: init-scripts
      configMap:
        name: fuel-bot-init-scripts
        defaultMode: 0644
